// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalysis = `-- name: GetAnalysis :many
WITH bucketed_measurements AS (
    SELECT
        r.name AS room,
        date_trunc('second', m.timestamp)::TIMESTAMP AS bucket,
        s.type,
        AVG(m.value)::DOUBLE PRECISION AS avg_val
    FROM measurements m
    JOIN sensors s ON m.sensor_id = s.id
    JOIN rooms r ON s.room_id = r.id
    GROUP BY 1, 2, 3
),
pivoted AS (
    SELECT
        room,
        bucket,
        MAX(CASE WHEN type = 'V' THEN avg_val END)::DOUBLE PRECISION AS v_val,
        MAX(CASE WHEN type = 'R' THEN avg_val END)::DOUBLE PRECISION AS r_val
    FROM bucketed_measurements
    GROUP BY 1, 2
)
SELECT
    room,
    bucket AS timestamp,
    (CASE 
        WHEN r_val = 0 THEN 0 
        WHEN v_val IS NULL OR r_val IS NULL THEN 0
        ELSE v_val / r_val 
    END)::DOUBLE PRECISION AS i_val,
    v_val,
    r_val
FROM pivoted
ORDER BY room, bucket
`

type GetAnalysisRow struct {
	Room      string
	Timestamp pgtype.Timestamp
	IVal      float64
	VVal      float64
	RVal      float64
}

func (q *Queries) GetAnalysis(ctx context.Context) ([]GetAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getAnalysis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalysisRow
	for rows.Next() {
		var i GetAnalysisRow
		if err := rows.Scan(
			&i.Room,
			&i.Timestamp,
			&i.IVal,
			&i.VVal,
			&i.RVal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoom = `-- name: GetRoom :one
SELECT id, name FROM rooms WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, name)
	var i Room
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSensor = `-- name: GetSensor :one
SELECT id, room_id, name, type FROM sensors WHERE name = $1 LIMIT 1
`

func (q *Queries) GetSensor(ctx context.Context, name string) (Sensor, error) {
	row := q.db.QueryRow(ctx, getSensor, name)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.Type,
	)
	return i, err
}

const insertMeasurement = `-- name: InsertMeasurement :one
INSERT INTO measurements (sensor_id, value, timestamp) VALUES ($1, $2, $3) RETURNING id, sensor_id, value, timestamp
`

type InsertMeasurementParams struct {
	SensorID  int32
	Value     float64
	Timestamp pgtype.Timestamp
}

func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) (Measurement, error) {
	row := q.db.QueryRow(ctx, insertMeasurement, arg.SensorID, arg.Value, arg.Timestamp)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.SensorID,
		&i.Value,
		&i.Timestamp,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertRoom(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, insertRoom, name)
	var i Room
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertSensor = `-- name: InsertSensor :one
INSERT INTO sensors (room_id, name, type) VALUES ($1, $2, $3) RETURNING id, room_id, name, type
`

type InsertSensorParams struct {
	RoomID int32
	Name   string
	Type   SensorType
}

func (q *Queries) InsertSensor(ctx context.Context, arg InsertSensorParams) (Sensor, error) {
	row := q.db.QueryRow(ctx, insertSensor, arg.RoomID, arg.Name, arg.Type)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.Type,
	)
	return i, err
}
